apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-piano-as-a-game-deployment
  labels:
    app: learn-piano-as-a-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learn-piano-as-a-game
  template:
    metadata:
      labels:
        app: learn-piano-as-a-game
    spec:
      containers:
        - name: learn-piano-as-a-game
          image: lucky97120/learn-piano-as-a-game:main
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: learn-piano-as-a-game
spec:
  type: NodePort
  selector:
    app: learn-piano-as-a-game
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learn-piano-as-a-game-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: maevalee.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learn-piano-as-a-game
                port:
                  number: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - maevalee.com
    secretName: maevalee-com-tls