apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-piano-as-a-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learn-piano-as-a-game
  template:
    metadata:
      labels:
        app: learn-piano-as-a-game
        version: IMAGE_LABEL
    spec:
      containers:
      - name: learn-piano-as-a-game
        image: lucky97120/learn-piano-as-a-game:latest #dockerhub already linked :pseudo/:image_name
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: learn-piano-as-a-game
spec:
  type: NodePort
  selector:
    app: learn-piano-as-a-game
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learn-piano-as-a-game
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learn-piano-as-a-game
                port:
                  number: 80

  ingressClassName: public